<a href="https://colab.research.google.com/github/jyotigiri7219/Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a = [1,2,5,"rahul"]
print(a)

[1, 2, 5, 'rahul']


In [ ]:
b = np.array([1,5,4])
print(b)

[1 5 4]


In [ ]:
c = np.array([1,2,5,"hr"])
print(c)

['1' '2' '5' 'hr']


In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
ap = np.array([[1,2,3],[4,5,6],[7,8,9]])
ap

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.zeros([10,5])
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones([2,6])
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.random.rand(2)


array([0.15460387, 0.15670494])

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[2,2] # single element

np.int64(13)

In [ ]:
scilc = arr[0:3,3:5] #multiple elements
scilc

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

In [ ]:
arr